### ISSUE TITLE
Error when "this" is not defined

### ISSUE THREAD

**Issue by brandonsoccer22** [spatie/server-side-rendering#62]
PR #49 seems to have introduced a bug when "this" is not defined.

Also for reference, I am compiling my code with Vite instead of Webpack.

Here is the error: 

```
Error Output:
================
file://storage/app/ssr/816a2e2ab307342d248eac819f1c3211.js:3
};(function () { if (this.process != null) { return; } this.process = { env: {}, argv: [] }; }).call(null);process.env.NODE_ENV = "production";process.env.VUE_ENV = "server";var context = {"url":"\/"};function ih(e){return e&&e.__esModule&&Object.prototype.hasOwnProperty.call(e,"default")?e.default:e}var Wc={exports:{}},xo={},Qc={exports:{}},I={};/**
                          ^

TypeError: Cannot read properties of null (reading 'process')
    at file://storage/app/ssr/816a2e2ab307342d248eac819f1c3211.js:3:27
    at file://storage/app/ssr/816a2e2ab307342d248eac819f1c3211.js:3:97
    at ModuleJob.run (node:internal/modules/esm/module_job:218:25)
    at async ModuleLoader.import (node:internal/modules/esm/loader:323:24)
    at async loadESM (node:internal/process/esm_loader:28:7)
    at async handleMainPromise (node:internal/modules/run_main:120:12)

Node.js v21.6.0.
```

I was able to fix this error by making the following change to `/src/Renderer.php` on [Line 191](https://github.com/spatie/server-side-rendering/blob/main/src/Renderer.php#L191):

```
'(function () { if (!this || this.process != null) { return; } this.process = { env: {}, argv: [] }; }).call(null)',
```
Basically, return early if `!this`

**Comment by zacwebb** [comment]
Same thing happening to me when using Vite
